[package]
name = "specta-rpc"
version = "0.0.0"
edition = "2021"

[dependencies]
specta = { path = "../../" }
paste = "1.0.14"

[dev-dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
